CREATE DATABASE api CHARSET utf8mb4;
USE api;

CREATE TABLE `user`(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
lastname VARCHAR(50),
firstname VARCHAR(50),
email VARCHAR(50) NOT NULL,
`password` VARCHAR(100) NOT NULL
)ENGINE=InnoDB;